### ISSUE TITLE
Text search over the index

### ISSUE THREAD

**Issue by oman-ispace** [agazzarini/SolRDF#106]
Hi,

Can I use SolRDF for performing text search on the created Solr index or is it only SPARQL queries that I run against the index. 

Duhai

**Comment by agazzarini** [comment]
Hi Duhai,
nice question...we already had a discussion about this topic, please see 
here [1] and here [2].
In addition, another user yesterday post a new topic [3] on the mailing 
list that could be interesting from this perspective: basically he 
merged the plain SolRDF Schema with the schema coming from Blacklight, 
which I think contains TextFields and therefore allows fulltext search.

The first question that comes on my mind is: what do you mean with "text 
search"? Is that something related only with object literals or you want 
to do that with URI, too? In this latter case (i.e. fulltext search on 
URIs), could you please expand a bit your needs?

Summarizing, with the current schema "text search" is not possible, as 
all members (i.e. fields) are indexed as strings. But, having said that, 
and seeing that there's a growing interest in this topic, I believe It 
would be great if you subscribe  the maililng list and reply to [1] or 
[3] (or directly open a new topic) so we can continue the discussion 
there (and involve the others as well)....maybe we could move this issue 
at the top of the todolist.

Best,
Andrea

[1] https://groups.google.com/forum/#!topic/solrdf-user-list/SmKCwkl4Vb4
[2] https://github.com/agazzarini/SolRDF/issues/69
[3] https://groups.google.com/forum/#!topic/solrdf-user-list/8UPAp7I4l7g

**Comment by agazzarini** [comment]
(referencing the issue #69 by @ahagenbruch)
