### ISSUE TITLE
Data import Issue

### ISSUE THREAD

**Issue by azeem87** [agazzarini/SolRDF#52]
After running 
curl -v http://localhost:8080/solr/store/update/bulk?commit=true \
-H "Content-Type: application/n-triples" \
--data-binary @/tmp/solrdf-download/solrdf/src/test/resources/sample-data/bsbm-generated-dataset.nt

I got this response

<?xml version="1.0" encoding="UTF-8"?>
response
    lst name="responseHeader">
        <int name="status">0</int>
        <int name="QTime">5</int>
    lst
response

But after when i check in solr admin ui , i am not able to see 5000 tuples. even i query with below stmt : 
curl "http://127.0.0.1:8080/solr/store/sparql" \
--data-urlencode "q=SELECT * WHERE { ?s ?p ?o } LIMIT 10" \
-H "Accept: application/sparql-results+xml"

i am getting this result with empty <results></results> tag

<?xml version="1.0"?>
sparql xmlns="http://www.w3.org/2005/sparql-results#"
  head
    variable name="s"
    <variable name="p"
    variable name="o"
  head
  results
  results
sparql

**Comment by azeem87** [comment]
webapp=/solr path=/update/bulk params={commit=true} status=0 QTime=5 , this was the reponse i get  when i push the content , when try to check with admin ui, no data is imported

**Comment by agazzarini** [comment]
If you're still running on Windows, I remember from a preceding issue 
that the project path is not under a /tmp folder
So most probably the path after @ in the curl command is not pointing to 
the sample dataset

Let me know.

In case it still doesn't work please paste the SolRDF console log, too

**Comment by azeem87** [comment]
i am trying this using postman rest client

**Comment by agazzarini** [comment]
Sorry I don't know it. So you aren't doing

After running
> curl -v http://localhost:8080/solr/store/update/bulk?commit=true \
> -H "Content-Type: application/n-triples" \
> --data-binary
> @/tmp/solrdf-download/solrdf/src/test/resources/sample-data/bsbm-generated-dataset.nt
>

If so,

- could you please give me the URL of such tool?
- are you sure you're indicating the right sample datafile path?
- could you please paste the SolRDF output log

Best,
Andrea

2015-04-07 12:04 GMT+02:00 azeem87 <notifications@github.com>:

**Comment by azeem87** [comment]
![image](https://cloud.githubusercontent.com/assets/11553172/7021184/d5425db2-dd3c-11e4-8b11-d35152350ca3.png)

**Comment by azeem87** [comment]
i am using chrome extension "postman" rest client.. u can try if u have chrome browser.

**Comment by agazzarini** [comment]
Ok, give me a minute, I will try to do the same

2015-04-07 12:14 GMT+02:00 azeem87 <notifications@github.com>:

**Comment by agazzarini** [comment]
Well, at first glance it seems that cURL and Postman are doing something different. cURL is sending the content of the file, not the file itself, while postman is not streaming the file content. 

What happening with cURL is like you choose "Raw" in postman and put the file content (1.2MB!) on the textarea. 

This is annoying because I thought on Solr side they were seen in the same way, but it is not so. Anyway, I think it is useful to have such capability so I'm working on that.

**Comment by azeem87** [comment]
Thank u so much. its working now

**Comment by agazzarini** [comment]
@azeem87 I just updated the master and the Wiki [1], too   

Briefly, using a slightly different sintax, and a plain GET request, you can send local or remote data:  

```
http://localhost:8080/solr/store/update/bulk?commit=true
&update.contentType=application/n-triples
&stream.file=(path to your local datafile)    
```
So you can issue this kind of request using the browser address bar, without going through Postman. Solr supports also a similar parameter (stream.url) for indexing remote resources    

Best and many thanks for pointing this.   
Andrea   

[1] https://github.com/agazzarini/SolRDF/wiki/User%20Guide#add-data

**Comment by agazzarini** [comment]
```
http://localhost:8080/solr/store/update/bulk?commit=true
&update.contentType=application/rdf%2Bxml
&stream.url=http://ec.europa.eu/eurostat/ramon/rdfdata/countries.rdf
```
