### ISSUE TITLE
SPARQL DESCRIBE ignores Accept Header

### ISSUE THREAD

**Issue by ahagenbruch** [agazzarini/SolRDF#60]
Hi @agazzarini, when sending DESCRIBE queries such as

```bash
curl -v http://localhost:8080/solr/store/sparql --data-urlencode 'q=DESCRIBE <http://zbw.eu/stw/thsys/72180>' -H 'Accept: text/turtle'
```
the Accept header is ignored and RDF/XML is being returned:

```bash
<SOLRDF-00092> : Query type 333, incoming Accept header is text/turtle, applied Content-type is application/rdf+xml
```

It would be nice if content negotiation worked for these queries, because some tools such as https://github.com/RubenVerborgh/N3.js don't process RDF/XML...

**Comment by agazzarini** [comment]
Hi @ahagenbruch,
That was a stupid mistake within solrconfig.xml:

```
			<!-- DESCRIBE -->
			<str name="333">application/rdf+xml,application/n-triples,text/turtles</str>
```

So *turtles" instead of "turtle" ;)

Now it should be ok

**Comment by ahagenbruch** [comment]
Yep, that was it! Thanks a lot...
