### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by michaeloa** [agazzarini/SolRDF#75]
What environment are the instructions done for?

I've been trying to test this, but on two different machines, I'm simply hitting dependency cannot be resolved errors on everything. These are ubuntu precise (12.04) machines, so thinking that it might simply be the environment is too old, and I need to find a 14.04 setup to run this on.

**Comment by agazzarini** [comment]
Hi Michael,
The environment is good, could you paste the error you're getting?
Dependency resolution seems something related with Maven.

Did you have a working internet connection on that machine? Maven is
somewhat "hairy" if it wasn't able to download some dependency...and
unfortunately just retrying after restablishing the connection doesn't work.

In case my assumption is right, you should remove all downloaded dependency:

# rm -rf $HOME/.m2/repository/*

And then retry with the installation (without cloning the repository)

Let me know

Andrea

**Comment by michaeloa** [comment]
Probably won't get around to looking at it any more this week (late). But I fired up a VM with 14.04, and that has now finished building and appears to be running fine. I'll take a look at it again on monday.

**Comment by agazzarini** [comment]
Ok nice to hear. However, as I said, I don't think the OS version had something to do with that.

If you will get some information on monday, please post them here.

Thanks

**Comment by agazzarini** [comment]
Hi @michaeloa, tomorrow I will put a "troubleshooting" section on the getting started page so we will close this issue ok?

**Comment by michaeloa** [comment]
Sure, no problem. Unfortunately, I didn't have time to look more closely at this today, except to try and throw up a compilation on a VM with Precise which failed (for a different reason than the OP). Since we're anyway going to be running SolR on 14.04 servers, it's not worthwhile for us to spend much more time trying to figure this one out.

Btw, regarding your #76, I found the installation instructions quite OK - though it would be useful to specify what envs its been tested on. I would think most technical users (and how many potential users are likely not to have tech competence) should be able to follow them.

I have someone in my team looking at building a simple website around a SolRDF database (forked the repo earlier today). We'll get back to you if we discover any other issues or find something to contribute.

**Comment by agazzarini** [comment]
Hi @michaeloa, sounds great. Another intersting option could also be to
provide a preinstalled VM image wth SolRDF.
About the fork, it would be great if who is investigating around SolRDF
(and in general anybody interested) could join the user and / or dev
mailing list



2015-05-18 23:24 GMT+02:00 Michael Akinde <notifications@github.com>:

**Comment by martin-voigt** [comment]
Hi,
hopefully in June I can give SolRDF a try and since we use Docker to encapsulate our services I will try to provide a Docker container fr SolRDF.

**Comment by agazzarini** [comment]
Wow, that would be absolutely great! I'm not expert on this topic, what 
is the "deliverable" artifact of such Docker thing? An image file? I 
setup a Dropbox account so we could put that stuff there

**Comment by michaeloa** [comment]
We've been looking at Docker in our current project, though we haven't moved to using it for production usage yet. But this would definitely be something we could find interesting to use, too.

**Comment by agazzarini** [comment]
Closing this issue after renaming of issue #76
