### ISSUE TITLE
Wrong content-type in sparql-results when /sparql is invoked from a web browser

### ISSUE THREAD

**Issue by agazzarini** [agazzarini/SolRDF#84]
The content-type in the scenario described in the summary should be set to text/xml or something that the browser is able to understand and display in a web page. At the moment the application/sparql-results+xml is not recognized so it causes (on browser side) the opening of the download / open pop-up.

**Comment by ahagenbruch** [comment]
Hmm, why sacrifice this more detailed (and correct) mime type for something that is convenient for only one type of client. People will probably not query SolRDF directly most of the time but via some proxy or web form, so I wouldn't call it a bug but a feature. ;-) Just my 2 cents...

**Comment by agazzarini** [comment]
@ahagenbruch +1 
To be honest I never called a SPARQL endpoint from a web browser :) so, after seeing this behaviour, I thought it is something more friendly than a command line. So I agree with you about the "nature" of the issue, it is a feature, not a bug  (just changed)

Thanks

**Comment by agazzarini** [comment]
I see a lot of SPARQL frontends (some links below) that can be installed in front of SolRDF with a minimum effort. Having said that, I agree with @ahagenbruch: implementing this issue would introduce a conditional logic just for handling this case, which is not how a SPARQL endpoint is usually invoked.        

http://yasgui.org    
http://www.ldodds.com/projects/twinkle    
http://laurensrietveld.nl/yasgui    
http://stackoverflow.com/questions/14434362/how-to-run-a-sparql-query
